---
# Ensures that an appropriate 'Chris' user is created

- hosts: chris-access
  user: root
  tasks:

  - name: create chris user
    user: name=chris

  - include: includes/ssh-keys user=chris key_dir=chris

  - name: deploy vimrc
    remote_user: chris
    copy: dest=~/.vimrc
          src=/etc/ansible/data/config/chris-vimrc

  - include: includes/install-fish

  - name: set default shell to fish
    user: name=chris shell=/usr/bin/fish
