---
# Adds SSH keys for root access

- hosts: dmdirc
  user: root
  tasks:

  - include: includes/ssh-keys user=root type=root key_dir=chris
  - include: includes/ssh-keys user=root type=root key_dir=greg
  - include: includes/ssh-keys user=root type=root key_dir=shane
